name: .NET build and test

on:
  push:
    branches: [ main ]
    paths-ignore:
    - README.md
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      reason:
        description: The reason for running the workflow
        required: true
        default: Manual run

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    
    - name: 'Print manual run reason'
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        echo 'Reason: ${{ github.event.inputs.reason }}'

    - name: Setup .NET
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: 7.0.x
    
    - uses: actions/cache@main
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }} #hash of project files
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore -c Release
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
